In [1]:
import numpy as np

In [4]:
# 1. np.array() - Listeyi NumPy dizisine çevirir
arr = np.array([1, 2, 3, 4, 5])
print("np.array():", arr)

np.array(): [1 2 3 4 5]


In [5]:
# 2. np.zeros() - Sıfırlardan oluşan bir dizi oluştur
zeros_arr = np.zeros((3, 3))
print("np.zeros():", zeros_arr)

np.zeros(): [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# 3. np.ones() - Birlerden oluşan bir dizi oluşturur
ones_arr = np.ones((2, 4))
print("np.ones():", ones_arr)

np.ones(): [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# 4. np.arange() - Belirli bir aralıkta düzenli artan sayılar üretir
range_arr = np.arange(0, 10, 2)
print("np.arange():", range_arr)

np.arange(): [0 2 4 6 8]


In [8]:
# 5. np.linspace() - Belirli iki sayı arasında eşit aralıklı sayılar üretir
linspace_arr = np.linspace(0, 10, 5)
print("np.linspace():", linspace_arr)

np.linspace(): [ 0.   2.5  5.   7.5 10. ]


In [9]:
# 6. np.eye() - Birim matris oluşturur
eye_arr = np.eye(3)
print("np.eye():", eye_arr)

np.eye(): [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# 7. np.random.rand() - 0 ile 1 arasında rastgele sayılar üretir
rand_arr = np.random.rand(3, 3)
print("np.random.rand():", rand_arr)

np.random.rand(): [[0.57766928 0.87054146 0.32534442]
 [0.06175288 0.70902605 0.03094117]
 [0.54459084 0.6333682  0.82975015]]


In [14]:
# 8. np.reshape() - Diziyi farklı bir şekle dönüştürür
reshaped_arr = np.arange(9).reshape(3, 3)
print("np.reshape():", reshaped_arr)

np.reshape(): [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
# 9. np.sum() - Dizinin toplamını hesaplar
sum_arr = np.sum(reshaped_arr)
print("np.sum():", sum_arr)

np.sum(): 36


In [16]:
# 10. np.mean() - Dizinin ortalamasını hesaplar
mean_arr = np.mean(reshaped_arr)
print("np.mean():", mean_arr)

np.mean(): 4.0


In [17]:
# 11. np.std() - Dizinin standart sapmasını hesaplar
std_arr = np.std(reshaped_arr)
print("np.std():", std_arr)

np.std(): 2.581988897471611


In [18]:
# 12. np.dot() - İki matrisin çarpımını hesaplar
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_product = np.dot(A, B)
print("np.dot():", dot_product)

np.dot(): [[19 22]
 [43 50]]
